# Generated by Django 4.2.5 on 2023-10-10 02:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('early', 'Early'), ('middle', 'Middle'), ('late', 'Late')], default='early', max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('progreso', models.PositiveIntegerField(default=0, help_text='Porcentaje de progreso del proyecto')),
                ('tareas_completadas', models.PositiveIntegerField(default=0)),
                ('tareas_totales', models.PositiveIntegerField(default=0)),
                ('asignado_a', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
