# Generated by Django 4.2.5 on 2023-10-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projects_fecha_entrega_projects_horas_trabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
