# Generated by Django 4.2.5 on 2023-10-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_tasks_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
