# Generated by Django 4.2.5 on 2023-10-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projects_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
