# Generated by Django 4.2.5 on 2023-10-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_tasks_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
