# Generated by Django 4.2.5 on 2023-10-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_tasks_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='tareas_completadas',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='tareas_totales',
        ),
    ]
