# Generated by Django 4.2.5 on 2023-10-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_projects_tareas_completadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='progreso',
        ),
    ]
