# Generated by Django 4.2.5 on 2023-10-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_projects_asignado_a_projects_asignado_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
