# Generated by Django 4.2.5 on 2023-10-12 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0016_alter_projects_fecha_finalizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='asignado_a',
        ),
        migrations.AddField(
            model_name='projects',
            name='asignado_a',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
